// spell-checker: ignore xact hashtext timestamptz bytea nonterminal jsonb trgm

namespace Sheddueller.Postgres.Internal;

using System.Globalization;

using Npgsql;

internal sealed class PostgresMigrator(ShedduellerPostgresOptions options) : IPostgresMigrator
{
    private readonly ShedduellerPostgresOptions _options = options;
    private readonly PostgresNames _names = new(options.SchemaName);

    public async ValueTask ApplyAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = await this._options.DataSource.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);

        await ExecuteAsync(
          connection,
          transaction,
          "select pg_advisory_xact_lock(7870833, hashtext(@schema_name));",
          command => command.Parameters.AddWithValue("schema_name", this._options.SchemaName),
          cancellationToken)
          .ConfigureAwait(false);

        await ExecuteAsync(connection, transaction, $"create schema if not exists {this._names.Schema};", cancellationToken).ConfigureAwait(false);
        await this.ApplyVersion1Async(connection, transaction, cancellationToken).ConfigureAwait(false);

        await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
    }

    private async ValueTask ApplyVersion1Async(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        CancellationToken cancellationToken)
    {
        await ExecuteAsync(
          connection,
          transaction,
          $"""
          create table if not exists {this._names.SchemaInfo} (
              singleton_id smallint primary key,
              schema_version integer not null,
              applied_at_utc timestamptz not null,
              constraint schema_info_singleton_id_check check (singleton_id = 1)
          );
          """,
          cancellationToken)
          .ConfigureAwait(false);

        var currentVersion = await this.GetCurrentVersionAsync(connection, transaction, cancellationToken).ConfigureAwait(false);
        if (currentVersion > PostgresNames.ExpectedSchemaVersion)
        {
            throw new InvalidOperationException(
              $"PostgreSQL schema '{this._options.SchemaName}' version {currentVersion} is newer than provider version {PostgresNames.ExpectedSchemaVersion}.");
        }

        await ExecuteAsync(connection, transaction, "create extension if not exists pg_trgm;", cancellationToken).ConfigureAwait(false);

        await ExecuteAsync(
          connection,
          transaction,
          $"""
          create table if not exists {this._names.Jobs} (
              job_id uuid primary key,
              state text not null,
              priority integer not null,
              enqueue_sequence bigint generated by default as identity unique,
              enqueued_at_utc timestamptz not null,
              not_before_utc timestamptz null,
              service_type text not null,
              method_name text not null,
              handler_search_text text generated always as (
                  service_type || E'\n' || method_name || E'\n' || split_part(service_type, ',', 1) || '.' || method_name
              ) stored,
              method_parameter_types text[] not null,
              invocation_target_kind text not null default 'Instance',
              method_parameter_bindings text[] null,
              serialized_arguments_content_type text not null,
              serialized_arguments bytea not null,
              attempt_count integer not null,
              max_attempts integer not null,
              retry_backoff_kind text null,
              retry_base_delay_ms bigint null,
              retry_max_delay_ms bigint null,
              claimed_by_node_id text null,
              claimed_at_utc timestamptz null,
              lease_token uuid null,
              lease_expires_at_utc timestamptz null,
              last_heartbeat_at_utc timestamptz null,
              completed_at_utc timestamptz null,
              failed_at_utc timestamptz null,
              canceled_at_utc timestamptz null,
              failure_type_name text null,
              failure_message text null,
              failure_stack_trace text null,
              source_schedule_key text null,
              scheduled_fire_at_utc timestamptz null,
              retry_clone_source_job_id uuid null,
              cancellation_requested_at_utc timestamptz null,
              cancellation_observed_at_utc timestamptz null,
              schedule_occurrence_kind text null,
              idempotency_key text null,
              job_event_sequence bigint not null default 0,
              constraint jobs_state_check check (state in ('Queued', 'Claimed', 'Completed', 'Failed', 'Canceled')),
              constraint jobs_invocation_target_kind_check check (invocation_target_kind in ('Instance', 'Static')),
              constraint jobs_attempt_count_check check (attempt_count >= 0),
              constraint jobs_max_attempts_check check (max_attempts >= 1),
              constraint jobs_retry_backoff_kind_check check (retry_backoff_kind is null or retry_backoff_kind in ('Fixed', 'Exponential')),
              constraint jobs_schedule_occurrence_kind_check check (schedule_occurrence_kind is null or schedule_occurrence_kind in ('Automatic', 'ManualTrigger'))
          );

          create table if not exists {this._names.JobConcurrencyGroups} (
              job_id uuid not null references {this._names.Jobs}(job_id) on delete cascade,
              group_key text not null,
              primary key (job_id, group_key)
          );

          alter table {this._names.Jobs}
              add column if not exists job_event_sequence bigint not null default 0,
              add column if not exists retry_clone_source_job_id uuid null,
              add column if not exists cancellation_requested_at_utc timestamptz null,
              add column if not exists cancellation_observed_at_utc timestamptz null,
              add column if not exists schedule_occurrence_kind text null,
              add column if not exists invocation_target_kind text not null default 'Instance',
              add column if not exists method_parameter_bindings text[] null,
              add column if not exists idempotency_key text null,
              add column if not exists handler_search_text text generated always as (
                  service_type || E'\n' || method_name || E'\n' || split_part(service_type, ',', 1) || '.' || method_name
              ) stored;

          alter table {this._names.Jobs}
              drop constraint if exists jobs_invocation_target_kind_check,
              add constraint jobs_invocation_target_kind_check check (invocation_target_kind in ('Instance', 'Static')),
              drop constraint if exists jobs_schedule_occurrence_kind_check,
              add constraint jobs_schedule_occurrence_kind_check check (schedule_occurrence_kind is null or schedule_occurrence_kind in ('Automatic', 'ManualTrigger'));

          create table if not exists {this._names.JobTags} (
              job_id uuid not null references {this._names.Jobs}(job_id) on delete cascade,
              ordinal integer not null,
              name text not null,
              value text not null,
              primary key (job_id, name, value),
              constraint job_tags_ordinal_check check (ordinal >= 0),
              constraint job_tags_name_check check (length(name) > 0),
              constraint job_tags_value_check check (length(value) > 0)
          );

          alter table {this._names.JobTags}
              add column if not exists ordinal integer;

          with ordered_tags as (
              select
                  job_id,
                  name,
                  value,
                  row_number() over (partition by job_id order by name asc, value asc) - 1 as ordinal
              from {this._names.JobTags}
              where ordinal is null
          )
          update {this._names.JobTags} tag
          set ordinal = ordered_tags.ordinal
          from ordered_tags
          where tag.job_id = ordered_tags.job_id
            and tag.name = ordered_tags.name
            and tag.value = ordered_tags.value;

          alter table {this._names.JobTags}
              alter column ordinal set not null,
              drop constraint if exists job_tags_ordinal_check,
              add constraint job_tags_ordinal_check check (ordinal >= 0);

          create table if not exists {this._names.ConcurrencyGroups} (
              group_key text primary key,
              configured_limit integer null,
              in_use_count integer not null,
              updated_at_utc timestamptz not null,
              constraint concurrency_groups_configured_limit_check check (configured_limit is null or configured_limit > 0),
              constraint concurrency_groups_in_use_count_check check (in_use_count >= 0)
          );

          create table if not exists {this._names.RecurringSchedules} (
              schedule_key text primary key,
              cron_expression text not null,
              is_paused boolean not null,
              overlap_mode text not null,
              priority integer not null,
              service_type text not null,
              method_name text not null,
              method_parameter_types text[] not null,
              invocation_target_kind text not null default 'Instance',
              method_parameter_bindings text[] null,
              serialized_arguments_content_type text not null,
              serialized_arguments bytea not null,
              retry_policy_configured boolean not null,
              max_attempts integer not null,
              retry_backoff_kind text null,
              retry_base_delay_ms bigint null,
              retry_max_delay_ms bigint null,
              next_fire_at_utc timestamptz null,
              created_at_utc timestamptz not null,
              updated_at_utc timestamptz not null,
              constraint recurring_schedules_overlap_mode_check check (overlap_mode in ('Skip', 'Allow')),
              constraint recurring_schedules_invocation_target_kind_check check (invocation_target_kind in ('Instance', 'Static')),
              constraint recurring_schedules_max_attempts_check check (max_attempts >= 1),
              constraint recurring_schedules_retry_backoff_kind_check check (retry_backoff_kind is null or retry_backoff_kind in ('Fixed', 'Exponential'))
          );

          alter table {this._names.RecurringSchedules}
              add column if not exists invocation_target_kind text not null default 'Instance',
              add column if not exists method_parameter_bindings text[] null;

          alter table {this._names.RecurringSchedules}
              drop constraint if exists recurring_schedules_invocation_target_kind_check,
              add constraint recurring_schedules_invocation_target_kind_check check (invocation_target_kind in ('Instance', 'Static'));

          create table if not exists {this._names.ScheduleConcurrencyGroups} (
              schedule_key text not null references {this._names.RecurringSchedules}(schedule_key) on delete cascade,
              group_key text not null,
              primary key (schedule_key, group_key)
          );

          create table if not exists {this._names.ScheduleTags} (
              schedule_key text not null references {this._names.RecurringSchedules}(schedule_key) on delete cascade,
              ordinal integer not null,
              name text not null,
              value text not null,
              primary key (schedule_key, name, value),
              constraint schedule_tags_ordinal_check check (ordinal >= 0),
              constraint schedule_tags_name_check check (length(name) > 0),
              constraint schedule_tags_value_check check (length(value) > 0)
          );

          alter table {this._names.ScheduleTags}
              add column if not exists ordinal integer;

          with ordered_tags as (
              select
                  schedule_key,
                  name,
                  value,
                  row_number() over (partition by schedule_key order by name asc, value asc) - 1 as ordinal
              from {this._names.ScheduleTags}
              where ordinal is null
          )
          update {this._names.ScheduleTags} tag
          set ordinal = ordered_tags.ordinal
          from ordered_tags
          where tag.schedule_key = ordered_tags.schedule_key
            and tag.name = ordered_tags.name
            and tag.value = ordered_tags.value;

          alter table {this._names.ScheduleTags}
              alter column ordinal set not null,
              drop constraint if exists schedule_tags_ordinal_check,
              add constraint schedule_tags_ordinal_check check (ordinal >= 0);

          create table if not exists {this._names.JobEvents} (
              job_id uuid not null references {this._names.Jobs}(job_id) on delete cascade,
              event_sequence bigint not null,
              event_id uuid not null unique,
              kind text not null,
              occurred_at_utc timestamptz not null,
              attempt_number integer not null,
              log_level text null,
              message text null,
              progress_percent double precision null,
              fields jsonb null,
              primary key (job_id, event_sequence),
              constraint job_events_kind_check check (kind in ('Lifecycle', 'AttemptStarted', 'AttemptCompleted', 'AttemptFailed', 'Log', 'Progress', 'CancelRequested', 'CancelObserved')),
              constraint job_events_attempt_number_check check (attempt_number >= 0),
              constraint job_events_log_level_check check (log_level is null or log_level in ('Trace', 'Debug', 'Information', 'Warning', 'Error', 'Critical')),
              constraint job_events_progress_percent_check check (progress_percent is null or (progress_percent >= 0 and progress_percent <= 100))
          );

          alter table {this._names.JobEvents}
              drop constraint if exists job_events_kind_check,
              add constraint job_events_kind_check check (kind in ('Lifecycle', 'AttemptStarted', 'AttemptCompleted', 'AttemptFailed', 'Log', 'Progress', 'CancelRequested', 'CancelObserved'));

          create table if not exists {this._names.WorkerNodes} (
              node_id text primary key,
              first_seen_at_utc timestamptz not null,
              last_heartbeat_at_utc timestamptz not null,
              max_concurrent_executions_per_node integer not null,
              current_execution_count integer not null,
              constraint worker_nodes_max_concurrency_check check (max_concurrent_executions_per_node > 0),
              constraint worker_nodes_current_execution_count_check check (current_execution_count >= 0)
          );

          create index if not exists idx_jobs_claim_scan
              on {this._names.Jobs} (priority desc, enqueue_sequence asc)
              where state = 'Queued';

          create index if not exists idx_jobs_due
              on {this._names.Jobs} (not_before_utc)
              where state = 'Queued';

          create index if not exists idx_jobs_lease_expiry
              on {this._names.Jobs} (lease_expires_at_utc)
              where state = 'Claimed';

          create index if not exists idx_jobs_source_schedule_nonterminal
              on {this._names.Jobs} (source_schedule_key)
              where state in ('Queued', 'Claimed');

          create unique index if not exists idx_jobs_queued_idempotency_key
              on {this._names.Jobs} (idempotency_key)
              where state = 'Queued' and idempotency_key is not null;

          create index if not exists idx_jobs_inspection_newest
              on {this._names.Jobs} (enqueue_sequence desc);

          create index if not exists idx_jobs_inspection_state_newest
              on {this._names.Jobs} (state, enqueue_sequence desc);

          create index if not exists idx_jobs_inspection_service_method
              on {this._names.Jobs} (service_type, method_name, enqueue_sequence desc);

          create index if not exists idx_jobs_inspection_handler_search_trgm
              on {this._names.Jobs} using gin (handler_search_text gin_trgm_ops);

          create index if not exists idx_jobs_inspection_source_schedule
              on {this._names.Jobs} (source_schedule_key, enqueue_sequence desc)
              where source_schedule_key is not null;

          create index if not exists idx_jobs_inspection_completed
              on {this._names.Jobs} (completed_at_utc desc)
              where completed_at_utc is not null;

          create index if not exists idx_jobs_inspection_failed
              on {this._names.Jobs} (failed_at_utc desc)
              where failed_at_utc is not null;

          create index if not exists idx_jobs_inspection_canceled
              on {this._names.Jobs} (canceled_at_utc desc)
              where canceled_at_utc is not null;

          create index if not exists idx_job_concurrency_groups_group_key
              on {this._names.JobConcurrencyGroups} (group_key);

          create index if not exists idx_job_tags_name_value_job_id
              on {this._names.JobTags} (name, value, job_id);

          create unique index if not exists idx_job_tags_job_id_ordinal
              on {this._names.JobTags} (job_id, ordinal);

          create index if not exists idx_schedule_tags_name_value_schedule_key
              on {this._names.ScheduleTags} (name, value, schedule_key);

          create unique index if not exists idx_schedule_tags_schedule_key_ordinal
              on {this._names.ScheduleTags} (schedule_key, ordinal);

          create index if not exists idx_job_events_job_sequence
              on {this._names.JobEvents} (job_id, event_sequence);

          create index if not exists idx_job_events_progress
              on {this._names.JobEvents} (job_id, event_sequence desc)
              where kind = 'Progress';

          create index if not exists idx_recurring_schedules_due
              on {this._names.RecurringSchedules} (next_fire_at_utc, schedule_key)
              where is_paused = false;

          create index if not exists idx_schedule_concurrency_groups_group_key
              on {this._names.ScheduleConcurrencyGroups} (group_key);

          create index if not exists idx_worker_nodes_last_heartbeat
              on {this._names.WorkerNodes} (last_heartbeat_at_utc);
          """,
          cancellationToken)
          .ConfigureAwait(false);

        await ExecuteAsync(
          connection,
          transaction,
          $"""
          insert into {this._names.SchemaInfo} (singleton_id, schema_version, applied_at_utc)
          values (1, @schema_version, transaction_timestamp())
          on conflict (singleton_id) do update
          set schema_version = excluded.schema_version,
              applied_at_utc = excluded.applied_at_utc;
          """,
          command => command.Parameters.AddWithValue("schema_version", PostgresNames.ExpectedSchemaVersion),
          cancellationToken)
          .ConfigureAwait(false);
    }

    private async ValueTask<int> GetCurrentVersionAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = $"select schema_version from {this._names.SchemaInfo} where singleton_id = 1;";

        var result = await command.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
        return result is null or DBNull ? 0 : Convert.ToInt32(result, CultureInfo.InvariantCulture);
    }

    internal static async ValueTask ExecuteAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        string commandText,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = commandText;
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    internal static async ValueTask ExecuteAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        string commandText,
        Action<NpgsqlCommand> configure,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = commandText;
        configure(command);
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }
}
